Updated publish script to be POSIX compliant

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -1,7 +1,13 @@
 #!/bin/sh -e
 
+err(){
+    echo "Unable to find the '$1' command."
+    echo "Install from PyPI, using '${PREFIX}pip install $1'."
+    exit 1
+}
+
 export PACKAGE="httpx"
-export VERSION=`cat ${PACKAGE}/__version__.py | grep __version__ | sed "s/__version__ = //" | sed "s/'//g"`
+export VERSION=$(grep __version__ "${PACKAGE}/__version__.py" | sed "s/__version__ = //" | sed "s/'//g")
 export PREFIX=""
 if [ -d 'venv' ] ; then
     export PREFIX="venv/bin/"
@@ -9,22 +15,16 @@ fi
 
 scripts/clean
 
-if ! command -v "${PREFIX}twine" &>/dev/null ; then
-    echo "Unable to find the 'twine' command."
-    echo "Install from PyPI, using '${PREFIX}pip install twine'."
-    exit 1
+if ! command -v "${PREFIX}twine" > /dev/null 2>&1 ; then
+    err twine
 fi
 
-if ! ${PREFIX}pip show wheel &>/dev/null ; then
-    echo "Unable to find the 'wheel' command."
-    echo "Install from PyPI, using '${PREFIX}pip install wheel'."
-    exit 1
+if ! ${PREFIX}pip show wheel > /dev/null 2>&1; then
+    err wheel
 fi
 
-if ! command -v "${PREFIX}mkdocs" &>/dev/null ; then
-    echo "Unable to find the 'mkdocs' command."
-    echo "Install from PyPI, using '${PREFIX}pip install mkdocs'."
-    exit 1
+if ! command -v "${PREFIX}mkdocs" > /dev/null 2>&1; then
+    err mkdocs
 fi
 
 find ${PACKAGE} -type f -name "*.py[co]" -delete
